language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t gustavelingsbo/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true gustavelingsbo/docker-react npm run test -- --coverage
